order/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import OrderListView, OrderCreat, OrderDetail, OrderMetaUpdate, order_search

urlpatterns = [
    path('', OrderListView, name="order-list"),
    path('create', OrderCreat, name="order-creat"),
    path('<pk>', OrderDetail, name="order-detail"),
    path('order-meta/<pk>', OrderMetaUpdate.as_view(), name="order-meta-status"),
    path('search/order', order_search, name="order-search")
]

telow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth import get_user_model
from main_app.models.process_model import process, process_action
from main_app.models.status_model import status
from main_app.models.customer_model import customer


# Create your models here.

class order(models.Model):
    # This model just save main data of orders like title, customer's name, priority, and etc
    
    INDEED_PRIORITY = [
        ("DO OR DIE", 'Do or die'),
        ("Critical", 'Critical priority'),
        ("High", 'High priority'),
        ("Middle", 'Middle priority'),
        ( "Low", 'Low priority'),
        
    ]
    
    order_title = models.CharField(max_length=100, unique=True)
    customer_id = models.ForeignKey(customer, null=True, on_delete=models.PROTECT)
    priority = models.CharField(max_length=11, choices=INDEED_PRIORITY, default="Low priority")
    process_id = models.ForeignKey(process, on_delete=models.SET_NULL, null=True)
    created_at  = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at  = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    def __str__(self):
        return self.order_title

class order_meta(models.Model):
    """
        other details of order in Fatty(OrderForm) form will save as a json with this model
    """
    
    order_id = models.OneToOneField(order, on_delete=models.CASCADE, primary_key=True)
    meta_value = models.JSONField(null=True)
    
    """
        because this app is just a local private service for our company,
        we need some custome permission to show each section of order form
        to related department
    """
    class Meta:
        permissions = [
            ("Can_view_litography", "can view litography details"),
            ("Can_view_paper", "can view paper details"),
            ("Can_view_hotstamp", "can view hotstamp details"),
            ("Can_view_befor_cut", "can view befor cut details"),
            ("Can_view_print",  "can view print details"),
            ("Can_view_hard_cover", "can view hard cover details"),
            ("Can_view_plastic_cover", "can view plastice cover details"),
            ("Can_view_part_cover", "can view part cover details"),
            ("Can_view_shield", "can view sheidl details"),
            ("Can_view_window_sticking", "can view window sticking details"),
            ("Can_view_box_sticking", "can view box sticking details"),
            ("Can_view_bindray", "can view bindray details"),
            ("Can_view_customize", "can view customize details"),
            ("Can_view_packaging", "can view packaging details")
            
        ]
    
    def __str__(self):
        return f" {self.order_id}"
    

class order_process_action(models.Model):
    """
        process actions are the actions that you declear and connect it to a process then 
        each order form have their own process actions
    """
    order_id = models.ForeignKey(order, on_delete=models.CASCADE)
    process_action = models.ForeignKey(process_action, on_delete=models.CASCADE)
    status = models.ForeignKey(status, on_delete=models.PROTECT, null=True,)
    created_at  = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at  = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    def __str__(self):
        return f"___ action: {self.process_action}, ___ status: {self.status} |"

order/views.py
from django.db.models import fields
from django.shortcuts import render, redirect
from main_app.models.action_model import Action, auth_user_action
from main_app.models.process_model import *
from order.models import order_meta 
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.contrib.auth.models import User
from order.models import order, order_process_action
import json
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from main_app.forms.forms import OrderMetaForm
from order.forms import OrderForm
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from jalali_date import datetime2jalali, date2jalali
from django.core.paginator import Paginator
from django.db.models import Q


order_success_url = "/dashboard/order/"

@login_required()
def OrderCreat(request):
    if request.user.has_perm("order.create_order"):
        if request.method == "GET":
            form = OrderForm()
            return render(request, "order/order_form.html", {"form": form, "title":'ساخت سفارش جدید'})
        if request.method == "POST":
            form = OrderForm(request.POST, request.FILES)
            if form.is_valid():
                files = request.FILES

                data = form.cleaned_data

                for file in files.items():
                    fs = FileSystemStorage()
                    filename = fs.save(file[1].name, file[1])
                    uploaded_file_url = fs.url(filename)
                    data[file[0]] = {
                        "name": file[1].name,
                        "location": uploaded_file_url,
                    }

                # hold model instance
                user_data = data["assignE"]
                flow_data = data["flow"]
                
                # serialize model instance to have json format
                data["flow"] = serializers.serialize("json", [data["flow"]])
                data["assignE"] = serializers.serialize("json", [data["assignE"]])
                data["delivery_date"] = data["delivery_date"].strftime("%Y/%m/%d")
                
                # create order record on order table
                # creating meta needs to have a new instance of order
                # for some reasons title of each order must be uniqe
                try:
                    new_order = order(
                        order_title=data["title"],
                        customer_id=user_data,
                        priority=data["priority"],
                        process_id=flow_data,
                    )
                    new_order.save()
                except Exception as e:
                    return JsonResponse({"Result": "BAD, when creating new order", "error": f"{e}"})
                # try to create order meta
                try:
                    data["operator"] = {
                        "username":request.user.username
                    }
                    new_order_meta = order_meta(order_id=new_order, meta_value=data)
                    new_order_meta.save()
                except Exception as e:
                    return JsonResponse({"Result": "BAD", "error": f"{e}"})

                # try to create order actions
                try:
                    actions = process_action.objects.filter(process_id=flow_data)
                    status_action = status.objects.get(status_title="در صف")
                    for index, action in enumerate(actions):
                        if index == 0:
                            new_order_meta = order_process_action(
                                order_id=new_order,
                                process_action=action,
                                status=status.objects.get(status_title="در دست بررسی"),
                            )
                        else:
                            new_order_meta = order_process_action(
                                order_id=new_order,
                                process_action=action,
                                status=status_action,
                            )
                        new_order_meta.save()
                except Exception as e:
                    return JsonResponse({"Result": "BAD", "error": f"{e}"})

                return redirect("order-list")

            else:
                return HttpResponse(f"{form.errors.as_json()} ")
    else:
        messages.add_message(
            request,
            messages.WARNING,
            "شما دسترسی لازم به این صفحه را ندارید",
            extra_tags="warning",
        )
        return redirect("order-list")


@login_required
def OrderDetail(request, pk):
    order_id = pk
    current_user = request.user
    current_order = order.objects.get(pk=pk)
    action_perms = auth_user_action.objects.filter(user_id=current_user).values_list(
        "action_id", flat=True
    )
    from main_app.models.status_model import status

    Status = status.objects.get(status_title="پایان یافته")
    actions2 = (
        order_process_action.objects.filter(process_action__action__in=action_perms)
        .filter(order_id=order_id)
        .all()
    )
    actions = order_process_action.objects.filter(order_id=current_order).order_by("process_action__priority").all()
    meta = order_meta.objects.filter(order_id=order_id).only("meta_value").get()
    users = json.loads(meta.meta_value["assignE"])
    meta.meta_value["assignE"] = users

    return render(
        request,
        "order/order_detail.html",
        {
            "order": current_order,
            "actions": actions,
            "UserActions": actions2,
            "meta": meta,
            "finished": Status,
            "title":"جزئیات سفارش"
        },
    )


@login_required
def OrderListView(request):
    order_list = order.objects.all()
    order_meta_list = []
    serialized_queryset = serializers.serialize("json", order_list)

    for order_metas in order_list:
        meta = (
            order_process_action.objects.filter(order_id=order_metas)
            .order_by("-updated_at")
            .first()
        )
        order_meta_list.append({"order": order_metas, "order_meta": meta})
    
    paginator = Paginator(order_meta_list, 6) # Show 10 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "order/order_list.html", {"orders": page_obj, "title":"لیست سفارشات"})


@method_decorator(login_required, name="dispatch")
class OrderMetaUpdate(UpdateView):
    template_name = "order/order_meta_form.html"
    model = order_process_action
    fields = ['status']
    title = "بروزرسانی سفارش"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        context['meta_form'] = OrderMetaForm
        context['obj'] = self.get_object()
        return context

    def post(self, request, *args, **kwargs):
        try:
            # get current obj from request
            obj_status_change = status.objects.filter(pk=int(request.POST.get('status'))).get()
            # update current obj status code
            current_obj = self.get_object()
            current_obj.status = obj_status_change
            current_obj.save()
            if obj_status_change.status_title == "پایان یافته":
                on_queue = status.objects.get(status_title='در دست بررسی')
                try:
                    next_obj = order_process_action.objects.filter(process_action__priority=current_obj.process_action.priority+1).filter(order_id=current_obj.order_id).first()
                    next_obj.status = on_queue
                    next_obj.save()
                except Exception as e:
                    pass
            else:
                return HttpResponse("NOOO")

            messages.add_message(
                request,
                messages.SUCCESS,
                "وعضعیت با موففیت تغییر یافت.",
                extra_tags="success",
            )
            return redirect('order-list')
        except Exception as e:
            messages.add_message(
                request,
                messages.WARNING,
                "عملیات موفیت آمیز نبود لطفا با ادمین تماس بگیرید.",
                extra_tags="danger",
            )
            return redirect('order-list')
        

    success_url = "/dashboard/order"

@login_required
def order_search(request):
    if request.method == "GET":
        if request.GET.get('q') is not None and request.GET.get('q') != u"":
            search_value = request.GET.get('q')
            query = order.objects.filter(Q(order_title__contains=search_value) | Q(customer_id__customer_name__contains=search_value) | Q(customer_id__customer_family__contains=search_value))
            list_data = []
            for data in query:
                temp_list_data = {"order_id":data.pk, "order_title":data.order_title, "customer":data.customer_id.customer_name+" "+data.customer_id.customer_family, "priority":data.priority, "process":data.process_id.process_name, "created_at": datetime2jalali(data.created_at).strftime(' - %Y/%m/%d - %H:%M')}
                list_data.append(temp_list_data)
        else:
            result = {"result": "None"}

        return JsonResponse(list_data,safe=False)

order/templates/order/order_list.html
{% extends "dashboard/base.html" %}
{% load jalali_tags %}
{% load tags %}
{% block content%}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="display-6">لیست سفارشات</h1>
    <div class="form-group row" dir="rtl">
        <label for="searchinput" class="col-sm-3 col-form-label">جستجو: </label>
        <div class="col-sm-9">
            <input type="text" class="form-control text-right" id="searchinput" placeholder="مثلا هری پاتر">
        </div>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href='{% url "order-creat" %}' class="btn btn-lg btn-outline-success">سفارش جدید</a>
            <a href='{% url "panel" %}' class="btn btn-lg btn-outline-primary">داشبورد</a>
        </div>
    </div>
</div>
<!-- Iterate over object_list -->
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.extra_tags}} alert-dismissible fade show mt-4" role="alert" dir="rtl">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
<div class="d-flex justify-content-md-between">
    <table class="table text-center table-striped table-bordered" dir="rtl">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">نام سفارش</th>
                <th scope="col">نام مشتری</th>

                <th scope="col">امکانات</th>
                <th scope="col">تاریخ ثبت سفارش</th>
            </tr>
        </thead>
        <tbody id="tableData" class="table-striped">
            {% for data in orders %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ data.order.order_title }}</td>
                <td>{{ data.order.customer_id}}</td>
                <td>
                    <a href='{% url "order-detail" data.order.pk %}' class="btn btn-secondary">جزئیات</a>
                </td>
                <td>{{ data.order.created_at|to_jalali:'%Y/%m/%d - %H:%M' }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<hr>
<div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2" role="group" aria-label="First group">
                {%if orders.has_previous %} {# whether the previous page exists #}
                <a class="btn btn-secondary text-white" href="?page={{orders.previous_page_number}}"><</a> {# link to the prev page #}
                {% endif %}
        </div>
        <div class="btn-group mr-2" role="group" aria-label="Second group">
            <button type="button" class="btn btn-secondary">{{orders.number}}</button>
        </div>
        <div class="btn-group" role="group" aria-label="Third group">
                {%if orders.has_next %} {# whether the next page exists #}
                <a class="btn btn-secondary text-white" href="?page={{orders.next_page_number}}">></a> {# link to the next page #}
                {% endif %}
        </div>
    </div>
</div>
<div class="d-flex justify-content-center">
    <div class="spinner-border spinner-border-lg" style="width: 4rem; height: 4rem;" role="status" id="spinner">
      <span class="sr-only">Loading...</span>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
$(document).ready(function () {
    var serchinput = $("#searchinput")
    var original = $("#tableData").html()
    var spinner = $("#spinner")
    spinner.hide()
    serchinput.on("input",function (e) {
        if (serchinput.val().length >= 2) 
        {
            spinner.show()
            $.ajax({
                method: 'GET',
                url: '{% url "order-search" %}',
                data: { q: serchinput.val() },
                success: function(res){
                    data = ""
                    if(res != "")
                    {
                        spinner.hide()
                        $.each(res, function(i, value){
                        data+= '<tr>\
                                <th scope="row">'+(i+1)+'</th>\
                                <td>'+value["order_title"]+'</td>\
                                <td>'+value["customer"]+'</td>\
                                <td>\
                                    <a href=/dashboard/order/'+value['order_id']+' class="btn btn-secondary">جزئیات</a>\
                                </td>\
                                <td>'+value["created_at"]+'</td>\
                            </tr>'
                            data += '<h1>'+value['order_title']+'</h1>'
                        })
                        $("#tableData").html(data)
                    }else
                    {
                        spinner.hide()
                        $("#tableData").html("اطلاعاتی یافت نشد")
                    }
                }  
            })
        }
        else if (serchinput.val().length<3){
            $("#tableData").html(original)
        }
    });
});


</script>
{% endblock %}

order/templates/order/order_meta_form.html
{% extends "dashboard/base.html"%}
{% block head %}
{{ block.super }}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="mt-5" dir="rtl">
                <h2 class="text-center">تغییر آیتم {{obj.process_action}}</h2>
                <form method="POST"  class="border p-5 rounded border-primary ">
                    <!-- Security token -->
                    {% csrf_token %}
        
                    {{meta_form.status}}
                    <input type="submit" value="ثبت" class="btn btn-success btn-block mt-4">
                    <a href="{% url 'order-list'%}" ><input type="button" value="انصراف" class="btn btn-block btn-danger  mt-2"></a>
        
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
{{block.super}}
<script>
    $('#id_status').addClass('js-example-basic-single form-control')
    $('#id_status').removeAttr('multiple')
</script>
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
    });
</script>
{% endblock %}