main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app.views.action_view import *
from main_app.views.status_view import *
from main_app.views.process_view import *
from main_app.views.department_view import *
from main_app.views.customer_view import *
from main_app.views.view import indexPanelView, logout_view
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path("", IndexView, name="index"),
    # route for panel/{service}/{id}/{task}
    path(
        "dashboard/",
        include(
            [
                path("order/", include("order.urls")),
                path("", indexPanelView, name="panel"),
                path(
                    "action/",
                    include(
                        [
                            path(
                                "",
                                ActionList,
                                name="action-list",
                            ),
                            path(
                                "add",
                                ActionCreate,
                                name="action-add",
                            ),
                            path(
                                "<pk>/update/",
                                ActionUpdate,
                                name="action-update",
                            ),
                            path(
                                "<pk>/delete/",
                                ActionDelete.as_view(),
                                name="action-delete",
                            ),
                        ]
                    ),
                ),
                path(
                    "status/",
                    include(
                        [
                            path(
                                "",
                                StatusList.as_view(),
                                name="status-list",
                            ),
                            path(
                                "add",
                                StatusCreate,
                                name="status-add",
                            ),
                            path(
                                "<pk>/update/",
                                StatusUpdate,
                                name="status-update",
                            ),
                            path(
                                "<pk>/delete/",
                                StatusDelete.as_view(),
                                name="status-delete",
                            ),
                        ]
                    ),
                ),
                path(
                    "process/",
                    include(
                        [
                            path("", 
                                 ProcessList.as_view(), 
                                 name="process-list"
                                 ),
                            path(
                                "add",
                                ProcessCreate,
                                name="process-add"
                            ),
                            path(
                                "<pk>", 
                                ProcessDetail, 
                                name="process-detail"
                            ),
                            path(
                                "<pk>/update",
                                ProcessUpdate,
                                name="process-update"
                            ),
                            path(
                                "<pk>/delete",
                                ProcessDelete.as_view(),
                                name="process-delete"
                            ),
                        ]
                    ),
                ),
                path(
                    "customer/",
                    include(
                        [
                            path("",
                                 CustomerList,
                                 name="customer-list"
                                 ),
                            path("add/",
                                 CustomerCreate,
                                 name="customer-add"
                                 ),
                            path(
                                "<pk>/update",
                                CustomerUpdate,
                                name="customer-update")  
                        ]
                    ),
                ),
            ],
        ),
        name="dashboard"
    ),
    path("logout/", logout_view, name="logout"),
]

handler404="main_app.views.view.handler404"
handler404="main_app.views.view.handler500"

order/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import OrderListView, OrderCreat, OrderDetail, OrderMetaUpdate, order_search

urlpatterns = [
    path('', OrderListView, name="order-list"),
    path('create', OrderCreat, name="order-creat"),
    path('<pk>', OrderDetail, name="order-detail"),
    path('order-meta/<pk>', OrderMetaUpdate.as_view(), name="order-meta-status"),
    path('search/order', order_search, name="order-search")
]

telow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models/action_model.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Action(models.Model):
    name        = models.CharField(max_length=55, unique=True)
    description = models.CharField(max_length=155)
    dependency   = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)
    created_at  = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at  = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    class Meta:
        ordering = ["pk"]
        
    def __str__(self):
        return self.name


class auth_user_action(models.Model):
    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    action_id = models.ForeignKey(Action, on_delete=models.CASCADE)
    
    class Meta:
        pass
    
    def __str__(self):
        return f" {self.user_id} "

main_app/models/customer_model.py
from django.db import models
from django.contrib.auth import get_user_model

class customer(models.Model):
    customer_name = models.CharField(max_length=55)
    customer_family = models.CharField(max_length=55)
    customer_mobile = models.CharField(max_length=11, unique=True)
    customer_phone = models.CharField(max_length=11, unique=True)
    operator = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=None, editable=False)
    created_at  = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at  = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    def __str__(self):
        return self.customer_name+" "+self.customer_family
    

main_app/models/department_model.py
from django.db import models

class department(models.Model):
    depart_name = models.CharField(max_length=55)
    depart_description = models.TextField()
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)

    def __str__(self):
        return self.depart_name

main_app/models/process_model.py
from django.db import models
from .action_model import Action
from .status_model import status

class process(models.Model):
    process_name = models.CharField(max_length=155, unique=True)
    process_description = models.CharField(max_length=500)
    isEnable = models.BooleanField(default=True)
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True, auto_now=True)

    def __str__(self):
        return self.process_name

class process_action(models.Model):
    action   = models.ForeignKey(Action, on_delete=models.PROTECT)
    process_id   = models.ForeignKey(process, on_delete=models.PROTECT, null=False, default="تعیین نشده")
    priority = models.PositiveIntegerField(null=True)
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True, auto_now=True)

    
    def __str__(self):
        return self.action.name

    
    

main_app/models/status_model.py
from django.db import models

class status(models.Model):
    status_title = models.CharField(max_length=55, default='تعیین نشده')
    description = models.CharField(max_length=55, null=True)
    color = models.CharField(max_length=7, null=True, default='e3e3e3')
    editable = models.BooleanField(null=False,default=True)
    created_at   = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at   = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    class Meta:
        ordering = ["pk"]
        
    def __str__(self):
        return self.status_title
    

main_app/views/action_view.py
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    CreateView,
)
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, Http404
from django.views import View
from ..models.action_model import Action, auth_user_action
from main_app.forms.forms import ActionForm
from main_app.models.process_model import process_action
from django.contrib import messages
from django.db.models import ProtectedError

# Create your views here.


def IndexView(request):
    return redirect('/dashboard/')


action_success_url = "/dashboard/action/"


@login_required()
def ActionList(request):
    if request.user.has_perm('main_app.view_action'):
        data = []
        actions = Action.objects.all()
        for action in actions:
            users = auth_user_action.objects.filter(action_id=action)
            print(action,users)
            data.append((action,users))
        print(data)
        return render(request, "main_app/action_list.html", {"object_list":data, "title":"لیست وظایف"})
    else:
        return redirect('index') 

@login_required()
def ActionUpdate(request, pk):
    if request.user.has_perm('main_app.edit_action'):
        from main_app.models.action_model import auth_user_action
        if request.method == "GET":
            action_instance = Action.objects.get(pk=pk)
            users = auth_user_action.objects.filter(action_id=action_instance)
            data = {
                "name": action_instance.name,
                "description": action_instance.description,
                "dependency": action_instance.dependency,
                "assignE": users.values_list('user_id', flat=True)
            }
            form = ActionForm(initial=data)
            return render(request, "main_app/action_form_update.html", {"form": form, "obj":action_instance, "title":"بروزرسانی وظایف"})
        
        if request.method == "POST":
            action_instance = Action.objects.get(pk=pk)
            form = ActionForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data.get('name')
                description = form.cleaned_data.get('description')
                dependency = form.cleaned_data.get('dependency')
                users = form.cleaned_data.get('assignE')
                action_instance.name = name
                action_instance.description = description
                action_instance.dependency = dependency
                action_instance.save()
                # delete all realted user permisions to action
                auth_user_action.objects.filter(action_id=action_instance).delete()
                
                for user in users:
                    new_auth_user_action = auth_user_action(user_id=user, action_id=action_instance)
                    new_auth_user_action.save()
                    
                # initial data to prepopulate form 
                users = auth_user_action.objects.filter(action_id=action_instance)

                data = {
                    "name": action_instance.name,
                    "description": action_instance.description,
                    "dependency": action_instance.dependency,
                    "assignE": users.values_list('user_id', flat=True)
                }
                form = ActionForm(initial=data)
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    f"{action_instance.name} به روزرسانی شد.",
                    extra_tags="success",
                )                
                return redirect('action-list')
    else:
        return redirect('index')    
    
@method_decorator(login_required, name="dispatch")
class ActionDelete(DeleteView):
    model = Action
    title = "حذف وظیفه"
    def dispatch(self, *args, **kwargs):
        if not (
            self.request.user.is_superuser or
            self.request.user.has_perm('main_app.delete_action') 
        ):
            return redirect('index')
        return super(ActionDelete, self).dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.success_url = action_success_url
        try:
            self.object.delete()
            messages.add_message(
                    request,
                    messages.SUCCESS,
                    f"وظیفه {self.object.name} با موفقیت حذف شد.",
                    extra_tags="success",
                )
            return redirect('action-list')
        except ProtectedError as e:
            messages.add_message(
                    request,
                    messages.ERROR,
                    f"وظیفه {self.object.name} دارای وظیفه وابسته است و یا روندی از این وظیفه استفاده می‌کند و امکان حذف آن وجود ندارد.",
                    extra_tags="Danger",
                )
            messages.add_message(
                    request,
                    messages.WARNING,
                    f'برای حذف وظیفه "{self.object.name}"  ابتدا وظیفه وابسته یا روندهای مرتبط با این وظیفه را را پاکسازی کنید',
                    extra_tags="warning",
                )
            return redirect('action-list')
    
    template_name = "main_app/action_confirm_delete.html"
    success_url = action_success_url

@login_required()
def ActionCreate(request):
    if request.user.has_perm('main_app.create_action'):
        from main_app.models.action_model import auth_user_action
        if request.method == "GET":
            form = ActionForm()
            return render(request, "main_app/action_form.html", {"form": form,"title":"ساخت وظیفه جدید"})
        if request.method == "POST":
            form = ActionForm(request.POST)
            if form.is_valid():
                name=form.cleaned_data.get('name')
                description=form.cleaned_data.get('description')
                dependency=form.cleaned_data.get('dependency')
                users = form.cleaned_data.get('assignE')
                new_action = Action(name=name, description=description, dependency=dependency)
                try:
                    new_action.save()
                except IntegrityError as e:
                    data = {
                        "name":name,
                        "description":description,
                        "dependency":dependency,
                        "assignE":users,
                    }
                    form = ActionForm(initial=data)
                    message = f"روند {name} از قبل وجود دارد. لطفا نام جدیدی انتخاب کنید."
                    return render(request, "main_app/action_form.html", {"form":form, "message":message, "status":"danger"})
                for user in users:
                    new_auth_user_action = auth_user_action(user_id=user, action_id=new_action)
                    new_auth_user_action.save()
                form = ActionForm()
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    "وظیفه جدید ساخته شد",
                    extra_tags="success",
                )
                return redirect("action-list")
    else:
        return redirect('index')    

main_app/views/department_view.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from main_app.models.department_model import department


# list department

def DepartmentList(request): 
    if request.user.has_perm('auth.delete_user'):
        department_list = department.objects.all()
        
        return render(request, "main_app/department/department_list.html")
    else:
        return redirect('index')

main_app/templates/dashboard/base.html
<html lang="en">
  {% load static %}
  <head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="M. Safarian">
  <title>{{title}}</title>
  <!-- Boostrap minimal core -->
  <link rel="stylesheet" href="{% static 'main_app/bootstrap/css/bootstrap.min.css' %}" >
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'main_app/bootstrap/js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript"
    src="{% static 'main_app/bootstrap/js/jquery.min.js' %}"></script>
  <script src="{% static 'main_app/bootstrap/js/jquery-3.5.1.slim.min.js' %}" ></script>
  <script src="{% static 'main_app/bootstrap/js/bootstrap.bundle.min.js' %}" ></script>

  <!-- date picker -->
  <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
  <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>

  <!-- Additional dashboard styles -->
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <style>
    body {
      font-size: .875rem;
    }

    .feather {
      width: 16px;
      height: 16px;
      vertical-align: text-bottom;
    }

    /*
 * Sidebar
 */

    .sidebar {
      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      z-index: 100;
      /* Behind the navbar */
      padding: 48px 0 0;
      /* Height of navbar */
      box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
    }

    @media (max-width: 767.98px) {
      .sidebar {
        top: 5rem;
      }
    }

    .sidebar-sticky {
      position: relative;
      top: 0;
      height: calc(100vh - 48px);
      padding-top: .5rem;
      overflow-x: hidden;
      overflow-y: auto;
      /* Scrollable contents if viewport is shorter than content. */
    }

    @supports ((position: -webkit-sticky) or (position: sticky)) {
      .sidebar-sticky {
        position: -webkit-sticky;
        position: sticky;
      }
    }

    .sidebar .nav-link {
      font-weight: 500;
      color: #333;
    }

    .sidebar .nav-link .feather {
      margin-right: 4px;
      color: #999;
    }

    .sidebar .nav-link.active {
      color: #007bff;
    }

    .sidebar .nav-link:hover .feather,
    .sidebar .nav-link.active .feather {
      color: inherit;
    }

    .sidebar-heading {
      font-size: .75rem;
      text-transform: uppercase;
    }

    /*
 * Navbar
 */

    .navbar-brand {
      padding-top: .75rem;
      padding-bottom: .75rem;
      font-size: 1rem;
      background-color: rgba(0, 0, 0, .25);
      box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
    }

    .navbar .navbar-toggler {
      top: .25rem;
      right: 1rem;
    }

    .navbar .form-control {
      padding: .75rem 1rem;
      border-width: 0;
      border-radius: 0;
    }

    .form-control-dark {
      color: #fff;
      background-color: rgba(255, 255, 255, .1);
      border-color: rgba(255, 255, 255, .1);
    }

    .form-control-dark:focus {
      border-color: transparent;
      box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
    }

    @font-face {
      font-family: iranYekan;
      src: url({% static '/main_app/fonts/iranyekanweblight.woff' %});
    }

    body {
      font-family: iranYekan;
    }
  </style>
  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/dashboard/">{{user}}</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
      data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
      </li>
    </ul>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse text-right" dir="rtl">
        <div class="sidebar-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" href='{% url "order-list" %}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 20 20 " fill="none"
                  stroke="currentColor" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"
                  class="bi bi-file-earmark" viewBox="0 0 16 16">
                  <path
                    d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5L14 4.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5h-2z" />
                </svg><span class="h4">سفارشات</span>
              </a>
            </li>
            {% if perms.main_app.view_status %}
            <li class="nav-item">
              <a class="nav-link" href='{% url "status-list"%}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 20 20" fill="none"
                  stroke="currentColor" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"
                  class="bi bi-stoplights">
                  <path
                    d="M8 5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zm0 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zm1.5 2.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                  <path
                    d="M4 2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2h2c-.167.5-.8 1.6-2 2v2h2c-.167.5-.8 1.6-2 2v2h2c-.167.5-.8 1.6-2 2v1a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-1c-1.2-.4-1.833-1.5-2-2h2V8c-1.2-.4-1.833-1.5-2-2h2V4c-1.2-.4-1.833-1.5-2-2h2zm2-1a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H6z" />
                </svg><span class="h4">وضیعت‌ها</span>
              </a>
            </li>
            {% endif %}
            {% if perms.main_app.view_action %}
            <li class="nav-item">
              <a class="nav-link" href='{% url "action-list" %}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 20 20" fill="none"
                  stroke="currentColor" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"
                  class="bi bi-tools">
                  <path
                    d="M1 0 0 1l2.2 3.081a1 1 0 0 0 .815.419h.07a1 1 0 0 1 .708.293l2.675 2.675-2.617 2.654A3.003 3.003 0 0 0 0 13a3 3 0 1 0 5.878-.851l2.654-2.617.968.968-.305.914a1 1 0 0 0 .242 1.023l3.356 3.356a1 1 0 0 0 1.414 0l1.586-1.586a1 1 0 0 0 0-1.414l-3.356-3.356a1 1 0 0 0-1.023-.242L10.5 9.5l-.96-.96 2.68-2.643A3.005 3.005 0 0 0 16 3c0-.269-.035-.53-.102-.777l-2.14 2.141L12 4l-.364-1.757L13.777.102a3 3 0 0 0-3.675 3.68L7.462 6.46 4.793 3.793a1 1 0 0 1-.293-.707v-.071a1 1 0 0 0-.419-.814L1 0zm9.646 10.646a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708zM3 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026L3 11z" />
                </svg><span class="h4">وظیفه</span>‌
              </a>
            </li>
            {% endif %}
            {% if perms.main_app.view_process %}
            <li class="nav-item">
              <a class="nav-link" href='{% url "process-list" %}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 20 20" fill="none"
                  stroke="currentColor" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"
                  class="bi bi-people">
                  <path fill-rule="evenodd"
                    d="M6 3.5A1.5 1.5 0 0 1 7.5 2h1A1.5 1.5 0 0 1 10 3.5v1A1.5 1.5 0 0 1 8.5 6v1H14a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0V8h-5v.5a.5.5 0 0 1-1 0V8h-5v.5a.5.5 0 0 1-1 0v-1A.5.5 0 0 1 2 7h5.5V6A1.5 1.5 0 0 1 6 4.5v-1zM8.5 5a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1zM0 11.5A1.5 1.5 0 0 1 1.5 10h1A1.5 1.5 0 0 1 4 11.5v1A1.5 1.5 0 0 1 2.5 14h-1A1.5 1.5 0 0 1 0 12.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm4.5.5A1.5 1.5 0 0 1 7.5 10h1a1.5 1.5 0 0 1 1.5 1.5v1A1.5 1.5 0 0 1 8.5 14h-1A1.5 1.5 0 0 1 6 12.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm4.5.5a1.5 1.5 0 0 1 1.5-1.5h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
                </svg> <span class="h4">روندها</span>
              </a>
            </li>
            {% endif %}
            {% if perms.main_app.view_customer %}
            <li class="nav-item">
              <a class="nav-link" href='{% url "customer-list" %}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 20 20" fill="none"
                  stroke="currentColor" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"
                  class="bi bi-people">
                  <path fill-rule="evenodd"
                    d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
                </svg> <span class="h4">مشتریان</span>
              </a>
            </li>
            {% endif %}
          </ul>
          </ul>
        </div>
      </nav>
      <main dir="ltr" role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 text-right">
          {% block content %}
          {% endblock %}
      </main>
    </div>
  </div>
{% block js %}
{% endblock %}
</body>
</html>